# Use an officical node.js runtime as a parent image
FROM node:22-alpine

# Set the working dir in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json .

# Install dependencies
RUN npm install

# Copy rest of the app code
COPY . .

# Expose the port that the app runs on
EXPOSE 3000

# Define the command to run your app
CMD [ "node", "./src/server.js" ]