### GET /
GET http://localhost:3000

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "samedo",
    "password": "helloworld"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "samedo",
    "password": "helloworld"
} 